com.instana.plugin.clickhouse:
  enabled: true
  user:
    valueFrom:
      secretKeyRef:
        name: passwords
        key: clickhouseuser
  password:
    valueFrom:
      secretKeyRef:
        name: passwords
        key: clickhousepassword
  protocol: http   # 'http' or 'https'
  host: localhost  # the host name or IP of the ClickHouse server
  httpPort: 8123   # the port of the ClickHouse server
  tracingEnabled: false
  profilingEnabled: false
  clusterName: instana
  poll_rate: 5 #Values are in seconds. Default Value 5 Sec.
  monitorTables:    # more in-depth metrics for these tables
    - 'shared.calls_v3'
